### ISSUE TITLE
[Taiwan/Taipei/大安] 華城電機股份有限公司 Rust Backend Engineer

### ISSUE THREAD

**Issue by vpochapuis** [rust-tw/jobs#2]
# Company

Fortune Electric - 華城電機股份有限公司

[CakeResume Profile](https://www.cakeresume.com/companies/fortune)
[Official Website](https://www.fortune.com.tw)

## 工作地點

Taipei Office, 臺北大安

## 遠端規定

NA

# Summary

We are looking for a skilled Backend Rust Engineer to join our team. The candidate should know Rust backend frameworks like Actix-Web, rust database ORMs like Diesel, and have a good understanding of Relational Databases like PostgreSQL. Knowledge in SQL, CI/CD, Git, Linux, multi-threading, and Rust Async programming is also essential. You will be responsible for developing and maintaining the Backend of a battery management system which is composed of several cross-field components. The project is quite multi-disciplinary and is a great opportunity to learn and work on different technical problems. The backend needs you to know how to manage threads and futures, design modular and reusable code, and create REST APIs as well as handling SSE(Server Sent Events). Effective communication and being a strong team player are crucial for this role. While not mandatory, knowledge of embedded systems, real-time operating systems, and serial communications like CAN and SPI would be quite valuable for this position. Our team as great interest in Open-Source technologies and contribution to the open-source community.

## 工作內容

1. **Backend Development:**
- Develop and maintain the backend of our systems in Rust. Ensure optimal performance and reliability while designing modular code. Write unit and integration tests.

2. **Database Integration:**
- Utilize Rust database ORM Diesel to interface with a Postgresql database. Write SQL migrations and manage a Postgresql Datase.

3. **CI/CD and Version Control:**
- Implement Continuous Integration/Continuous Deployment (CI/CD) pipelines and use Git for version control. We are currently using Gitea Actions (same as Github actions) for our CI.

4. **Linux Environment:**
- Work within a Linux environment, configuring and maintaining the distribution of your choice.

5. **Team Collaboration:**
- Collaborate effectively with cross-functional teams and fellow engineers to deliver high-quality software solutions. Work in collaboration with the Frontend Team to design REST APIs and other web communication channels like SSE

## 能力需求

- Bachelor's or higher degree in Computer Science, Software Engineering, or a related field.
- Proficiency in Rust, Actix-Web, and Diesel ORM.
- Strong knowledge of relational databases, particularly PostgreSQL, and expertise in SQL.
- Experience with CI/CD pipelines and Git for version control.
- Familiarity with Linux environments and system configuration.
- Capability to work with multi-threading and Rust Async programming.
- Previous experience in REST API development.
- Effective communication skills and a strong team player.
- Nice to have: Knowledge of embedded systems, real-time operating systems, and serial communications like CAN and SPI.

## 薪資範圍

40,000 ~ 90,000 TWD / month

## 工時

Monday to Friday, 8 hours a day, 40 hours a week.

## 聯絡方式

For applying: [Official CakeResume Job Listing](https://www.cakeresume.com/companies/fortune/jobs/taipei-backend-engineer)

For more information: Technical Project Manager email vincent.chapuis@fortune.com.tw

**Comment by sharils** [comment]
Close as a duplicate.

**Comment by sharils** [comment]
Close as duplicate.
